# Generated by Django 4.2.11 on 2024-04-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('ati', 'Ativo'), ('ina', 'Inativo')], default='ati', max_length=8),
        ),
    ]
