# Generated by Django 4.2.11 on 2024-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usuario_tipo_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('fis', 'Pessoa Fisica'), ('jud', 'Pessoa Juridica')], max_length=8),
        ),
    ]
