# Generated by Django 4.2.11 on 2024-04-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_usuario_cep_usuario_cidade_usuario_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone Celular:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_fixo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Fixo:'),
        ),
    ]
