# Generated by Django 4.2.11 on 2024-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usuario_cep_alter_usuario_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telefone_fixo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone Comercial:'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone Celular:'),
        ),
    ]
