# Generated by Django 4.2.11 on 2024-04-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_usuario_telefone_fixo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf_cnpj',
            field=models.CharField(default=47614966813, max_length=14),
            preserve_default=False,
        ),
    ]
