# Generated by Django 4.2.11 on 2024-04-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usuario_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
