# Generated by Django 4.2.13 on 2024-05-23 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='status',
        ),
    ]
