# Generated by Django 4.2.13 on 2024-05-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='rg',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
