# Generated by Django 4.2.13 on 2024-05-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_data_nascimento_clients_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='logradouro',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='telefone_celular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone Celular:'),
        ),
        migrations.AddField(
            model_name='clients',
            name='telefone_comercial',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Telefone Comercial:'),
        ),
    ]
