# Generated by Django 4.2.13 on 2024-05-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clients_cep_clients_cidade_clients_complemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='tipo',
            field=models.CharField(choices=[('fis', 'Pessoa Fisica'), ('jud', 'Pessoa Juridica')], max_length=8, null=True),
        ),
    ]
