# Generated by Django 4.2.13 on 2024-05-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='veiculos',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Veiculos:'),
        ),
    ]
