# Generated by Django 4.2.11 on 2024-05-31 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clients_veiculos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='veiculos',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='clients.clients'),
            preserve_default=False,
        ),
    ]
