# Generated by Django 4.2.11 on 2024-06-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_clients_veiculos_vehicle_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='brands',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cliente',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='clients',
            name='tipo',
            field=models.CharField(choices=[('fis', 'Pessoa Física'), ('jud', 'Pessoa Jurídica')], max_length=8, null=True),
        ),
    ]
